AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Octank Analytics Alexa Skills

Globals:
  Function:
    Timeout: 10

Resources:
  Analytics:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: analytics/
      Handler: app.handler
      Runtime: nodejs8.10
